server:
  port: 28080
  name: "xxxx"
database:
  host: localhost
  port: 3306
  username: root
  password: root
nacos:
  servers:
    - ipAddr: localhost
      port: 8848
      scheme: http
      contextPath: /nacos
  client:
    namespaceId: "123"
    timeout: 3000
    logDir: "logs/nacos/log"
    cacheDir: "tmp/nacos/cache"
    logLevel: "debug"
grpc:
  ip: '0.0.0.0'
  port: 38080
